- name: Configure Docker all hosts
  hosts: servers
  become: true
  gather_facts: false
  roles:
    - ansible-role-docker

- name: Kopiëren docker-compose naar VM
  hosts: servers
  become: yes
  vars:
    local_file: "docker/docker-compose.yaml"
    remote_path: "/home/testuser/docker-compose.yaml"  
  tasks:
    - name: Kopiëren van bestand
      become: yes
      copy:
        src: "{{ local_file }}"
        dest: "{{ remote_path }}"
        mode: '0644'

    - name: Deploy Docker container
      become: yes
      command: |
        docker-compose -f /home/testuser/docker-compose.yaml up -d
