name: Execute Ansible Playbook and Deploy Docker container

on:
  push:
  workflow_dispatch:

jobs:
  release-image:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: execute ansible playbook
        run: |
          ansible-playbook -i inventory.ini main.yml 

